#! /bin/sh

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# polybar
$HOME/.config/polybar/launch.sh

# background configuration
feh --bg-scale ~/Pictures/Wallpapers/wp1.png

bspc monitor -d I II III IV V
bspc config top_padding 				20
bspc config border_width        2
bspc config window_gap          8
bspc config focused_border_color "#1d3b53"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
